a = input( 'Digite algo: ')
print('O tipo primitivo desse valor é', type(a))
print('Só tem espaços ?', a.isspace())
print('Ele é alphanúmerico ?',a.isalnum())
print('Ele é alfabético ?', a.isalpha())
print('É um número ?', a.isnumeric())
print('Esta em maiusculas ?',a.isupper())
print('Esta em minusculas ?', a.islower())
print('Esta capitalizada',a.istitle())

